backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
collections:
  - name: "startseite"
    label: "Startseite"
    files:
      - file: "data/de/banner.yml"
        label: "herobanner"
        name: "Hero Banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "text" },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Aktive", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" }
            ]}]}
