backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
collections:
  - name: "startseite"
    label: "Startseite"
    files:
      - file: "data/de/banner.yml"
        label: "Hero Banner"
        name: "herobanner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "text" },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Aktive", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" }
            ]}]}
      - file: "data/de/funfacts.yml"
        label: "Funfacts"
        name: "funfacts"
        fields:
          - { label: "Funfacts", name: "funfacts", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Fakten", name: "counter_item", widget: "list", fields: [
              { label: "Titel", name: "title", widget: "string" },
              { label: "Icon", name: "icon", widget: "string" },
              { label: "Count", name: "count", widget: "string" }
            ] } ] }
      - file: "data/de/terrazzo.yml"
        label: "Terrazzo"
        name: "terrazzo"
        fields:
          - { label: "Terrazzo", name: "terrazzo", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Bild links", name: "image", widget: "image" },
            { label: "Title", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "text" },
            { label: "Benefits", name: "benefits", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: "string" },
              { label: "Titel", name: "title", widget: "string" },
              { label: "Content", name: "content", widget: "string" }
            ]},
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Aktive", name: "enable", widget: "boolean", default: true },
              { label: "Link", name: "link", widget: "string" },
              { label: "Label", name: "label", widget: "string" }
            ]}] }
      - file: "data/de/sichtspachtelmasse.yml"
        label: "Sichtspachtelmasse"
        name: "sichtspachtelmasse"
        fields:
          - { label: "Sichtspachtelmasse", name: "sichtspachtelmasse", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Bild links", name: "image", widget: "image" },
            { label: "Title", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "text" },
            { label: "Benefits", name: "benefits", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: "string" },
              { label: "Titel", name: "title", widget: "string" },
              { label: "Content", name: "content", widget: "string" }
            ] },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Aktive", name: "enable", widget: "boolean", default: true },
              { label: "Link", name: "link", widget: "string" },
              { label: "Label", name: "label", widget: "string" }
            ] } ] }
      - file: "data/de/professional.yml"
        label: "Professional"
        name: "professional"
        fields:
          - { label: "Professional", name: "professional", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Title", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "text" },
            { label: "Items", name: "items", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: "string" },
              { label: "Titel", name: "item", widget: "string" },
              { label: "Content", name: "content", widget: "text" },
              { label: "Image", name: "bg_image", widget: "image" }
            ] } ] }
      - file: "data/de/jobscta.yml"
        label: "Jobs CTA"
        name: "jobscta"
        fields:
          - { label: "CTA", name: "cta", widget: "object", fields: [
            { label: "Aktive", name: "enable", widget: "boolean", default: true },
            { label: "Image", name: "bg_image", widget: "image" },
            { label: "Title", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "markdown" },
            { label: "Button", name: "button", widget: "list", fields: [
              { label: "Aktive", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" }
            ] } ] }